### ISSUE TITLE
gptTurbo

### ISSUE THREAD

**Issue by MeleMannen** [FuturraGroup/OpenAI#1]
Hi! I am trying your new OpenAI API and I found a problem that the gptTurbo don't seem to be working. When ever I try to use it, it returns an error. The others work fine!

**Comment by sergey-zhuravel** [comment]
What is your error? Show a screenshot and a screenshot of the request. We checked we have no errors.

**Comment by MeleMannen** [comment]
Here is my request:

Here is my error:
error: requestFailed(Error Domain=NSURLErrorDomain Code=404 "(null)")


lør. 11. mar. 2023 kl. 10:12 skrev Sergey Zhuravel ***@***.***

**Comment by MeleMannen** [comment]
Here is my request: 
![Bilde 11 03 2023 klokken 15 00](https://user-images.githubusercontent.com/113589968/224489227-13fb1786-67f8-4bfc-a0a1-358349605804.jpg)

My error is: requestFailed(Error Domain=NSURLErrorDomain Code=404 "(null)")

**Comment by kyrylo-mukha** [comment]
> Here is my request: ![Bilde 11 03 2023 klokken 15 00](https://user-images.githubusercontent.com/113589968/224489227-13fb1786-67f8-4bfc-a0a1-358349605804.jpg)
> 
> My error is: requestFailed(Error Domain=NSURLErrorDomain Code=404 "(null)")

Hi. This error means that this model (gpt-3.5-turbo) not compatible with this endpoint.

More information about compatibility you can see [here](https://platform.openai.com/docs/models/model-endpoint-compatability) in OpenAI documentation.

If you want use gpt-3.5-turbo model - you can use _**sendChatCompletion**_ method from latest update. It works almost the same as _**sendCompletion**_.

Thank you for reporting. For prevent confusions like this we will add more readable information provided in error in nearest update.

**Comment by kyrylo-mukha** [comment]
We've published update 1.1.2 with more detailed information in error to prevent confusions and updated documentation about compatibility.

**Comment by MeleMannen** [comment]
Great! Thanks for the help and a very quick response that is much
appreciated!

lør. 11. mar. 2023 kl. 21:49 skrev Mukha Kirill ***@***.***>:
