### ISSUE TITLE
The operation couldn’t be completed. (NSURLErrorDomain error 401.)

### ISSUE THREAD

**Issue by ankushdhawan** [FuturraGroup/OpenAI#10]
i am getting this error "The operation couldn’t be completed. (NSURLErrorDomain error 401.)" can you help me for same

**Comment by kyrylo-mukha** [comment]
Hi. Can you provide more detailed information. Cast error as NSError and provide information from userData.
401 error it's unauthorized error. This output will provide more detailed information. Looks like you using wrong API token or your token for some reason unauthorized to use this model or endpoint.

Thank you.

**Comment by ankushdhawan** [comment]
No My token is valid and when i am calling rest api by using same token it is working. But when i am calling below function with same token i am getting 401 error.
openAI.sendChatCompletion(newMessage: AIMessage(role: .user, content: prompt), previousMessages: [], model: .gptV3_5(.gptTurbo), maxTokens: 2048, n: 1, completion: { [weak self] result in
            DispatchQueue.main.async { self?.stopLoading() }
            
            switch result {
            case .success(let aiResult):
                // Handle result actions
                if let text = aiResult.choices.first?.message?.content {
                    print(text)
                }
            case .failure(let error):
                // Handle error actions
                print(error.localizedDescription)
            }
        })

**Comment by kyrylo-mukha** [comment]
Cast error as NSError and provide information from userData field.

**Comment by ankushdhawan** [comment]
it is working now. you can close this
