### ISSUE TITLE
Inspired by MacPaw/OpenAI?

### ISSUE THREAD

**Issue by Krivoblotsky** [FuturraGroup/OpenAI#2]
Hey, @sergey-zhuravel, @kirillmukha.

I came across this repository and see that it's literally copied (inspired?) by https://github.com/MacPaw/OpenAI
Would you mind changing the design, or leaving a note where it got inspiration from? What do you think?

<img width="784" alt="Screenshot 2023-03-25 at 12 54 23" src="https://user-images.githubusercontent.com/1411778/227712976-1fcd0df2-451b-4bd8-bdb1-820f0f3fb4c8.png">
<img width="781" alt="Screenshot 2023-03-25 at 12 54 00" src="https://user-images.githubusercontent.com/1411778/227712980-3ba7fba3-1802-44f0-8e0b-4d5a48e44056.png">

Btw, I see pretty much inspiration on Futurra Github home page along with MacPaw one as well.

**Comment by sergey-zhuravel** [comment]
hi, our design team really made a picture in the same style as on your page. I will ask them to make changes and in the near future we will replace the picture.
Thanks for the feedback!
