### ISSUE TITLE
Hi! I am trying your new OpenAI API and I found a problem that the Api don't seem to be working. When ever I try to use it, it returns an error. 

### ISSUE THREAD

**Issue by zzzzzero6** [FuturraGroup/OpenAI#5]
Hi! I am trying your new OpenAI API and I found a problem that the Api don't seem to be working. When ever I try to use it, it returns an error.
<img width="997" alt="截屏2023-11-04 14 45 57" src="https://github.com/FuturraGroup/OpenAI/assets/149862380/15859152-b986-4196-8d89-5a41ffae0f9f">
<img width="991" alt="截屏2023-11-04 14 47 19" src="https://github.com/FuturraGroup/OpenAI/assets/149862380/3c741830-6614-4495-b04e-6f4b6db1e10f">

**Comment by kyrylo-mukha** [comment]
Hi. Can you provide more detailed information. Cast error as NSError and provide information from userData. 
401 error it's unauthorized error. This output will provide more detailed information. Looks like you using wrong API token or your token for some reason unauthorized to use this model or endpoint. 

Thank you.
