### ISSUE TITLE
JSON mode feature

### ISSUE THREAD

**Issue by DavidZomada** [FuturraGroup/OpenAI#7]
Hello, OpenAI community. I hope you are doing well. 

I'm currently working on an application using the OpenAIKit library, and I've found it to be an excellent tool for interfacing with the OpenAI GPT models. However, I have a specific use case that requires the implementation of the [JSON mode](https://platform.openai.com/docs/guides/text-generation/json-mode) feature recently introduced by OpenAI. I'm contacting the community to see if there's interest in extending the OpenAIKit library to support this specific use case. 

I will attempt to create a pull request myself. It would be my first contribution to a public library so, I might need some help.

If anyone in the community is interested in collaborating on this feature or has suggestions on how to improve the implementation, I would greatly appreciate your input. Let's work together to make OpenAIKit even more powerful and accessible.

Thank you for your time and consideration.

Best regards.

**Comment by kyrylo-mukha** [comment]
Hi. I apologize for a long time answer.
The JSON response format feature already implemented in version [1.7.0](https://github.com/FuturraGroup/OpenAI/releases/tag/1.7.0) of OpenAIKit.
I'm sorry we are not documented it well in [README.md](https://github.com/FuturraGroup/OpenAI/blob/main/README.md). We'll update it ASAP.
Now you can look for parameter **_responseFormat_** in request. That will return you JSON string from OpenAI.
Thank you for contacting us.
