### ISSUE TITLE
Error 401 when I try to use the API

### ISSUE THREAD

**Issue by sarahsvitlik03** [FuturraGroup/OpenAI#9]
Hi !! I followed this tutorial and added some modifications to the view I made and created a model to interact between the Controller and view. Now, I am trying to type into my SparkGPTView and I am getting this error:  **the operation could not be completed, NSURLError domain error 404**.  

It looks like the error is generating in my sendQuestion view model function -

    func sendQuestion() {
        isLoading = true
        response = ""
        
        let prompt = text
        openAI.sendChatCompletion(newMessage: AIMessage(role: .user, content: prompt), previousMessages: previousMessages, model: .gptV3_5(.gptTurbo), maxTokens: 2048, n: 1) { [weak self] result in
            DispatchQueue.main.async {
                self?.isLoading = false
                switch result {
                case .success(let aiResult):
                    if let text = aiResult.choices.first?.message?.content {
                        self?.response = text
                    }
                case .failure(let error):
                    self?.response = "Error: \(error.localizedDescription)"
                }
            }
        }
    }
}

I am not familiar with this API and am just starting out in iOS Development so I am not sure what the problem is. I for sure have the right API key. 

Here is the link to the specific folder in my project with the ChatGPT API usage - 

1. https://github.com/UNH-iOS-Spring2024/DateSpark-S24--SvitlikRussell/tree/main/DateSpark/SparkGPT
2. https://github.com/UNH-iOS-Spring2024/DateSpark-S24--SvitlikRussell/blob/main/DateSpark/DateSparkApp.swift

![Screenshot 2024-04-07 at 12 31 58 PM](https://github.com/FuturraGroup/OpenAI/assets/89283653/0c9bd94e-2bea-44c8-b595-b4144dfa3728)

**Comment by kyrylo-mukha** [comment]
Hi. Can you provide more detailed information. Cast error as NSError and provide information from userData.
401 error it's unauthorized error. This output will provide more detailed information. Looks like you using wrong API token or your token for some reason unauthorized to use this model or endpoint.

Thank you.
